revan -a -n -f ./sources/simTra_files/HomogeneousBeam8keV_PHEMTO_config1.inc2.id1.sim.gz -g /local/home/jf285468/Documents/PHEMTO/new/instruments/PHEMTO_config1.geo.setup -c revan.cfg
revan -a -n -f ./sources/simTra_files/HomogeneousBeam30keV_PHEMTO_config1.inc2.id1.sim.gz -g /local/home/jf285468/Documents/PHEMTO/new/instruments/PHEMTO_config1.geo.setup -c revan.cfg
revan -a -n -f ./sources/simTra_files/HomogeneousBeam50keV_PHEMTO_config1.inc2.id1.sim.gz -g /local/home/jf285468/Documents/PHEMTO/new/instruments/PHEMTO_config1.geo.setup -c revan.cfg
revan -a -n -f ./sources/simTra_files/HomogeneousBeam80keV_PHEMTO_config1.inc2.id1.sim.gz -g /local/home/jf285468/Documents/PHEMTO/new/instruments/PHEMTO_config1.geo.setup -c revan.cfg
revan -a -n -f ./sources/simTra_files/HomogeneousBeam100keV_PHEMTO_config1.inc2.id1.sim.gz -g /local/home/jf285468/Documents/PHEMTO/new/instruments/PHEMTO_config1.geo.setup -c revan.cfg
revan -a -n -f ./sources/simTra_files/HomogeneousBeam120keV_PHEMTO_config1.inc2.id1.sim.gz -g /local/home/jf285468/Documents/PHEMTO/new/instruments/PHEMTO_config1.geo.setup -c revan.cfg
revan -a -n -f ./sources/simTra_files/HomogeneousBeam150keV_PHEMTO_config1.inc2.id1.sim.gz -g /local/home/jf285468/Documents/PHEMTO/new/instruments/PHEMTO_config1.geo.setup -c revan.cfg
revan -a -n -f ./sources/simTra_files/HomogeneousBeam200keV_PHEMTO_config1.inc2.id1.sim.gz -g /local/home/jf285468/Documents/PHEMTO/new/instruments/PHEMTO_config1.geo.setup -c revan.cfg
revan -a -n -f ./sources/simTra_files/HomogeneousBeam250keV_PHEMTO_config1.inc2.id1.sim.gz -g /local/home/jf285468/Documents/PHEMTO/new/instruments/PHEMTO_config1.geo.setup -c revan.cfg
revan -a -n -f ./sources/simTra_files/HomogeneousBeam300keV_PHEMTO_config1.inc2.id1.sim.gz -g /local/home/jf285468/Documents/PHEMTO/new/instruments/PHEMTO_config1.geo.setup -c revan.cfg
revan -a -n -f ./sources/simTra_files/HomogeneousBeam400keV_PHEMTO_config1.inc2.id1.sim.gz -g /local/home/jf285468/Documents/PHEMTO/new/instruments/PHEMTO_config1.geo.setup -c revan.cfg
revan -a -n -f ./sources/simTra_files/HomogeneousBeam500keV_PHEMTO_config1.inc2.id1.sim.gz -g /local/home/jf285468/Documents/PHEMTO/new/instruments/PHEMTO_config1.geo.setup -c revan.cfg
revan -a -n -f ./sources/simTra_files/HomogeneousBeam600keV_PHEMTO_config1.inc2.id1.sim.gz -g /local/home/jf285468/Documents/PHEMTO/new/instruments/PHEMTO_config1.geo.setup -c revan.cfg
