revan -a -n -f Pol80keV.inc1.id1.sim.gz -g /Users/miguelmoita/OneDrive/Work/Ferrara/ASTENAMegalib/Geometries/NFT_Pathfinder_4L.geo.setup -c revan.cfg
revan -a -n -f NoPol80keV.inc1.id1.sim.gz -g /Users/miguelmoita/OneDrive/Work/Ferrara/ASTENAMegalib/Geometries/NFT_Pathfinder_4L.geo.setup -c revan.cfg
revan -a -n -f Pol100keV.inc1.id1.sim.gz -g /Users/miguelmoita/OneDrive/Work/Ferrara/ASTENAMegalib/Geometries/NFT_Pathfinder_4L.geo.setup -c revan.cfg
revan -a -n -f NoPol100keV.inc1.id1.sim.gz -g /Users/miguelmoita/OneDrive/Work/Ferrara/ASTENAMegalib/Geometries/NFT_Pathfinder_4L.geo.setup -c revan.cfg
revan -a -n -f Pol120keV.inc1.id1.sim.gz -g /Users/miguelmoita/OneDrive/Work/Ferrara/ASTENAMegalib/Geometries/NFT_Pathfinder_4L.geo.setup -c revan.cfg
revan -a -n -f NoPol120keV.inc1.id1.sim.gz -g /Users/miguelmoita/OneDrive/Work/Ferrara/ASTENAMegalib/Geometries/NFT_Pathfinder_4L.geo.setup -c revan.cfg
revan -a -n -f Pol150keV.inc1.id1.sim.gz -g /Users/miguelmoita/OneDrive/Work/Ferrara/ASTENAMegalib/Geometries/NFT_Pathfinder_4L.geo.setup -c revan.cfg
revan -a -n -f NoPol150keV.inc1.id1.sim.gz -g /Users/miguelmoita/OneDrive/Work/Ferrara/ASTENAMegalib/Geometries/NFT_Pathfinder_4L.geo.setup -c revan.cfg
revan -a -n -f Pol200keV.inc1.id1.sim.gz -g /Users/miguelmoita/OneDrive/Work/Ferrara/ASTENAMegalib/Geometries/NFT_Pathfinder_4L.geo.setup -c revan.cfg
revan -a -n -f NoPol200keV.inc1.id1.sim.gz -g /Users/miguelmoita/OneDrive/Work/Ferrara/ASTENAMegalib/Geometries/NFT_Pathfinder_4L.geo.setup -c revan.cfg
revan -a -n -f Pol250keV.inc1.id1.sim.gz -g /Users/miguelmoita/OneDrive/Work/Ferrara/ASTENAMegalib/Geometries/NFT_Pathfinder_4L.geo.setup -c revan.cfg
revan -a -n -f NoPol250keV.inc1.id1.sim.gz -g /Users/miguelmoita/OneDrive/Work/Ferrara/ASTENAMegalib/Geometries/NFT_Pathfinder_4L.geo.setup -c revan.cfg
revan -a -n -f Pol300keV.inc1.id1.sim.gz -g /Users/miguelmoita/OneDrive/Work/Ferrara/ASTENAMegalib/Geometries/NFT_Pathfinder_4L.geo.setup -c revan.cfg
revan -a -n -f NoPol300keV.inc1.id1.sim.gz -g /Users/miguelmoita/OneDrive/Work/Ferrara/ASTENAMegalib/Geometries/NFT_Pathfinder_4L.geo.setup -c revan.cfg
revan -a -n -f Pol400keV.inc1.id1.sim.gz -g /Users/miguelmoita/OneDrive/Work/Ferrara/ASTENAMegalib/Geometries/NFT_Pathfinder_4L.geo.setup -c revan.cfg
revan -a -n -f NoPol400keV.inc1.id1.sim.gz -g /Users/miguelmoita/OneDrive/Work/Ferrara/ASTENAMegalib/Geometries/NFT_Pathfinder_4L.geo.setup -c revan.cfg
revan -a -n -f Pol500keV.inc1.id1.sim.gz -g /Users/miguelmoita/OneDrive/Work/Ferrara/ASTENAMegalib/Geometries/NFT_Pathfinder_4L.geo.setup -c revan.cfg
revan -a -n -f NoPol500keV.inc1.id1.sim.gz -g /Users/miguelmoita/OneDrive/Work/Ferrara/ASTENAMegalib/Geometries/NFT_Pathfinder_4L.geo.setup -c revan.cfg
revan -a -n -f Pol600keV.inc1.id1.sim.gz -g /Users/miguelmoita/OneDrive/Work/Ferrara/ASTENAMegalib/Geometries/NFT_Pathfinder_4L.geo.setup -c revan.cfg
revan -a -n -f NoPol600keV.inc1.id1.sim.gz -g /Users/miguelmoita/OneDrive/Work/Ferrara/ASTENAMegalib/Geometries/NFT_Pathfinder_4L.geo.setup -c revan.cfg
